version: "3.9"

services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=alizadeh
      - POSTGRES_PASSWORD=1234
    volumes:
      - todo-app-postgres-data:/var/lib/postgresql/data/


volumes:
    todo-app-postgres-data:



