# Generated by Django 4.1.6 on 2023-03-15 10:08

from django.db import migrations



def create_default_rows(apps, schema_editor):
    MyModel = apps.get_model('home', 'Priority')
    MyModel.objects.create(priority = "important")
    MyModel.objects.create(priority = "tolerable")
    MyModel.objects.create(priority = "whatever")



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_task_priority'),
    ]

    operations = [
    ]
